resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/JonathanMabiala/concourse-pipeline.git
    branch: dev

jobs:
  - name: hello-world-job
    plan: # represents steps
      - get: repo
        trigger: true
      - task: hello-world-task # represents a step
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
          - name: repo
          run:
            path: cat
            args: ["repo/README.md"]
